# Generated by Django 4.1.2 on 2023-09-01 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0003_ignitz_delete_bala'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_Id', models.IntegerField()),
                ('Student_Names', models.CharField(max_length=100)),
                ('Present_Date', models.DateField()),
                ('Status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mail_Id', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='ignitz',
            name='Any_Backlogs',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ignitz',
            name='Candidate_Name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ignitz',
            name='Father_Name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ignitz',
            name='Hometown',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ignitz',
            name='Referred_By',
            field=models.CharField(max_length=100),
        ),
    ]
