# Generated by Django 4.1.2 on 2023-09-09 06:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0004_attendance_login_alter_ignitz_any_backlogs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ignitz',
            name='Mobile_number',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='Present_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='Status',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Excused', 'Excused')], max_length=100),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='Student_Id',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999999)]),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='Student_Names',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='ignitz',
            name='Any_Backlogs',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(0)]),
        ),
        migrations.AlterField(
            model_name='ignitz',
            name='Btech_Percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='ignitz',
            name='Candidate_Name',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='ignitz',
            name='College_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='ignitz',
            name='Father_Name',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='ignitz',
            name='Hometown',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='ignitz',
            name='Passed_out_year',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='ignitz',
            name='Qualification',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='ignitz',
            name='Referred_By',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='ignitz',
            name='Stream',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
    ]
