# Generated by Django 4.1.2 on 2023-09-09 07:05

import app2.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0005_remove_ignitz_mobile_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ignitz',
            name='Mobile_Number',
            field=models.BigIntegerField(default=0, validators=[app2.models.validate_mobile_number]),
        ),
    ]
