# Generated by Django 4.2.4 on 2023-09-14 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0006_ignitz_mobile_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=30)),
                ('confim_password', models.CharField(max_length=30)),
            ],
        ),
    ]
