# Generated by Django 4.2.4 on 2023-09-15 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0007_studentpassword'),
    ]

    operations = [
        migrations.CreateModel(
            name='StdLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('susername', models.CharField(max_length=20)),
                ('spassword', models.CharField(max_length=30)),
            ],
        ),
        migrations.RenameField(
            model_name='login',
            old_name='Password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='login',
            old_name='Mail_Id',
            new_name='username',
        ),
    ]
