# Generated by Django 4.2.4 on 2023-09-25 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0008_stdlogin_rename_password_login_password_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stdlogin',
            old_name='spassword',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='stdlogin',
            old_name='susername',
            new_name='username',
        ),
    ]
