# Generated by Django 4.2.4 on 2023-09-25 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0009_rename_spassword_stdlogin_password_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StdLogin',
        ),
    ]
